# Generated by Django 3.1.7 on 2021-04-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sala_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='projector_is_available',
            new_name='projector',
        ),
    ]
