# Generated by Django 3.1.7 on 2021-04-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_app', '0008_reserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='commentar',
        ),
        migrations.AddField(
            model_name='reserve',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
