# Generated by Django 3.1.7 on 2021-04-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sala_app', '0009_auto_20210419_1756'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserve',
            unique_together={('room_id', 'date')},
        ),
    ]
